--
-- PostgreSQL database dump
--

\restrict yng2optORXtRyh6Znfnlhj3fihmNqgEnxTZuCJIWjMjamgIRbsYcW8fgskViK5n

-- Dumped from database version 16.13 (Homebrew)
-- Dumped by pg_dump version 18.2 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ccr; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ccr (
    course_code character varying(15) NOT NULL,
    course_name character varying(150) NOT NULL,
    course_type character varying(10) NOT NULL,
    semester smallint NOT NULL,
    academic_year character varying(9) NOT NULL,
    term smallint NOT NULL,
    lecture_hrs smallint NOT NULL,
    tutorial_hrs smallint NOT NULL,
    practical_hrs smallint NOT NULL,
    total_hrs smallint,
    credits smallint NOT NULL,
    int_weightage smallint NOT NULL,
    ese_weightage smallint NOT NULL,
    ese_mode character varying(15) NOT NULL,
    ese_duration_hrs smallint NOT NULL,
    ese_max_marks smallint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    faculty_id character varying(10) NOT NULL,
    program_id bigint NOT NULL,
    is_submitted boolean NOT NULL,
    is_deprecated boolean NOT NULL,
    is_locked boolean NOT NULL,
    allow_cross_semester boolean NOT NULL,
    CONSTRAINT ccr_semester_check CHECK (((semester >= 1) AND (semester <= 12))),
    CONSTRAINT ccr_weightage_positive CHECK (((int_weightage >= 0) AND (ese_weightage >= 0))),
    CONSTRAINT weightage_check CHECK (((int_weightage + ese_weightage) = 100))
);


--
-- Name: course_exam_stats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_exam_stats (
    id bigint NOT NULL,
    academic_year character varying(9) NOT NULL,
    attempt_type character varying(15) NOT NULL,
    total_registered integer NOT NULL,
    total_appeared integer NOT NULL,
    total_absent integer NOT NULL,
    total_pass integer NOT NULL,
    total_fail integer NOT NULL,
    total_withheld integer NOT NULL,
    pass_rate numeric(5,2) NOT NULL,
    avg_marks numeric(6,2),
    computed_at timestamp with time zone NOT NULL,
    course_id character varying(15) NOT NULL,
    CONSTRAINT course_exam_stats_total_absent_check CHECK ((total_absent >= 0)),
    CONSTRAINT course_exam_stats_total_appeared_check CHECK ((total_appeared >= 0)),
    CONSTRAINT course_exam_stats_total_fail_check CHECK ((total_fail >= 0)),
    CONSTRAINT course_exam_stats_total_pass_check CHECK ((total_pass >= 0)),
    CONSTRAINT course_exam_stats_total_registered_check CHECK ((total_registered >= 0)),
    CONSTRAINT course_exam_stats_total_withheld_check CHECK ((total_withheld >= 0))
);


--
-- Name: course_exam_stats_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_exam_stats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_exam_stats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course_unlock_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_unlock_log (
    id bigint NOT NULL,
    reason text NOT NULL,
    unlocked_at timestamp with time zone NOT NULL,
    course_id character varying(15) NOT NULL,
    unlocked_by_id bigint
);


--
-- Name: course_unlock_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_unlock_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_unlock_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: exam_attempt; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exam_attempt (
    id bigint NOT NULL,
    attempt_type character varying(15) NOT NULL,
    attempt_no smallint NOT NULL,
    academic_year character varying(9) NOT NULL,
    conducted_on date,
    status character varying(12) NOT NULL,
    remarks text,
    entered_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL,
    course_id character varying(15) NOT NULL,
    entered_by character varying(10),
    student_id character varying(10) NOT NULL,
    ese_marks numeric(6,2),
    CONSTRAINT exam_attempt_attempt_no_check CHECK ((attempt_no >= 0))
);


--
-- Name: exam_attempt_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exam_attempt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_attempt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: faculty; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.faculty (
    faculty_id character varying(10) NOT NULL,
    name character varying(150) NOT NULL,
    department character varying(150),
    created_at timestamp with time zone NOT NULL,
    school_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: faculty_of; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.faculty_of (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    short_name character varying(30),
    created_at timestamp with time zone NOT NULL
);


--
-- Name: faculty_of_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.faculty_of ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.faculty_of_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ia_component; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ia_component (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    weightage numeric(5,2) NOT NULL,
    max_marks numeric(6,2) NOT NULL,
    mode character varying(15) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    course_id character varying(15) NOT NULL
);


--
-- Name: ia_component_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ia_component ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ia_component_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: marks_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.marks_entry (
    id bigint NOT NULL,
    marks_obtained numeric(6,2),
    scaled_marks numeric(6,2),
    entered_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL,
    component_id bigint NOT NULL,
    entered_by character varying(10),
    student_id character varying(10) NOT NULL,
    attempt_type character varying(15) NOT NULL
);


--
-- Name: marks_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.marks_entry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marks_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: program; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.program (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    short_name character varying(20) NOT NULL,
    duration_yrs smallint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    school_id bigint NOT NULL
);


--
-- Name: program_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.program ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.program_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: result_sheet; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.result_sheet (
    id bigint NOT NULL,
    int_total numeric(6,2),
    ese_marks numeric(6,2),
    grand_total numeric(6,2),
    computed_at timestamp with time zone NOT NULL,
    course_id character varying(15) NOT NULL,
    student_id character varying(10) NOT NULL,
    pass_status character varying(12) NOT NULL,
    active_attempt_type character varying(15) NOT NULL,
    ese_pass_status character varying(12) NOT NULL,
    ia_pass_status character varying(12) NOT NULL
);


--
-- Name: result_sheet_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.result_sheet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.result_sheet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: school; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    short_name character varying(30),
    created_at timestamp with time zone NOT NULL,
    faculty_of_id bigint NOT NULL
);


--
-- Name: school_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.school ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.school_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student (
    student_id character varying(10) NOT NULL,
    roll_no character varying(15) NOT NULL,
    gender character varying(6) NOT NULL,
    semester smallint NOT NULL,
    section character varying(10),
    academic_year character varying(9) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    program_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT student_semester_check CHECK (((semester >= 1) AND (semester <= 12)))
);


--
-- Name: student_backlog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_backlog (
    id bigint NOT NULL,
    reason character varying(10) NOT NULL,
    status character varying(8) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    clearing_attempt_id bigint,
    course_id character varying(15) NOT NULL,
    origin_attempt_id bigint,
    student_id character varying(10) NOT NULL
);


--
-- Name: student_backlog_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.student_backlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_backlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_enrolment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_enrolment (
    id bigint NOT NULL,
    academic_year character varying(9) NOT NULL,
    enrolled_at timestamp with time zone NOT NULL,
    course_id character varying(15) NOT NULL,
    student_id character varying(10) NOT NULL,
    admin_override boolean NOT NULL,
    ese_eligible boolean NOT NULL
);


--
-- Name: student_enrolment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.student_enrolment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_enrolment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    jlu_id character varying(15) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    email character varying(150) NOT NULL,
    role character varying(10) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    must_change_password boolean NOT NULL
);


--
-- Name: users_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: users_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: ccr ccr_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ccr
    ADD CONSTRAINT ccr_pkey PRIMARY KEY (course_code);


--
-- Name: course_exam_stats course_exam_stats_course_id_academic_year__7aa616de_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_exam_stats
    ADD CONSTRAINT course_exam_stats_course_id_academic_year__7aa616de_uniq UNIQUE (course_id, academic_year, attempt_type);


--
-- Name: course_exam_stats course_exam_stats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_exam_stats
    ADD CONSTRAINT course_exam_stats_pkey PRIMARY KEY (id);


--
-- Name: course_unlock_log course_unlock_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_unlock_log
    ADD CONSTRAINT course_unlock_log_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: exam_attempt exam_attempt_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_attempt
    ADD CONSTRAINT exam_attempt_pkey PRIMARY KEY (id);


--
-- Name: exam_attempt exam_attempt_student_id_course_id_att_09519681_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_attempt
    ADD CONSTRAINT exam_attempt_student_id_course_id_att_09519681_uniq UNIQUE (student_id, course_id, attempt_type, attempt_no);


--
-- Name: faculty_of faculty_of_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.faculty_of
    ADD CONSTRAINT faculty_of_name_key UNIQUE (name);


--
-- Name: faculty_of faculty_of_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.faculty_of
    ADD CONSTRAINT faculty_of_pkey PRIMARY KEY (id);


--
-- Name: faculty faculty_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.faculty
    ADD CONSTRAINT faculty_pkey PRIMARY KEY (faculty_id);


--
-- Name: faculty faculty_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.faculty
    ADD CONSTRAINT faculty_user_id_key UNIQUE (user_id);


--
-- Name: ia_component ia_component_course_id_name_5bfa660a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ia_component
    ADD CONSTRAINT ia_component_course_id_name_5bfa660a_uniq UNIQUE (course_id, name);


--
-- Name: ia_component ia_component_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ia_component
    ADD CONSTRAINT ia_component_pkey PRIMARY KEY (id);


--
-- Name: marks_entry marks_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marks_entry
    ADD CONSTRAINT marks_entry_pkey PRIMARY KEY (id);


--
-- Name: marks_entry marks_entry_student_id_component_id_attempt_type_1fc434fe_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marks_entry
    ADD CONSTRAINT marks_entry_student_id_component_id_attempt_type_1fc434fe_uniq UNIQUE (student_id, component_id, attempt_type);


--
-- Name: program program_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.program
    ADD CONSTRAINT program_pkey PRIMARY KEY (id);


--
-- Name: program program_school_id_short_name_0f3633a2_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.program
    ADD CONSTRAINT program_school_id_short_name_0f3633a2_uniq UNIQUE (school_id, short_name);


--
-- Name: result_sheet result_sheet_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.result_sheet
    ADD CONSTRAINT result_sheet_pkey PRIMARY KEY (id);


--
-- Name: result_sheet result_sheet_student_id_course_id_4e8194a5_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.result_sheet
    ADD CONSTRAINT result_sheet_student_id_course_id_4e8194a5_uniq UNIQUE (student_id, course_id);


--
-- Name: school school_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school
    ADD CONSTRAINT school_name_key UNIQUE (name);


--
-- Name: school school_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school
    ADD CONSTRAINT school_pkey PRIMARY KEY (id);


--
-- Name: student_backlog student_backlog_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_backlog
    ADD CONSTRAINT student_backlog_pkey PRIMARY KEY (id);


--
-- Name: student_enrolment student_enrolment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_enrolment
    ADD CONSTRAINT student_enrolment_pkey PRIMARY KEY (id);


--
-- Name: student_enrolment student_enrolment_student_id_course_id_aca_845f7e3c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_enrolment
    ADD CONSTRAINT student_enrolment_student_id_course_id_aca_845f7e3c_uniq UNIQUE (student_id, course_id, academic_year);


--
-- Name: student student_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_pkey PRIMARY KEY (student_id);


--
-- Name: student student_roll_no_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_roll_no_key UNIQUE (roll_no);


--
-- Name: student student_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_user_id_key UNIQUE (user_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users_groups users_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_pkey PRIMARY KEY (id);


--
-- Name: users_groups users_groups_user_id_group_id_fc7788e8_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_group_id_fc7788e8_uniq UNIQUE (user_id, group_id);


--
-- Name: users users_jlu_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_jlu_id_key UNIQUE (jlu_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_user_id_permission_id_3b86cbdf_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_permission_id_3b86cbdf_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: ccr_course_code_533722f6_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ccr_course_code_533722f6_like ON public.ccr USING btree (course_code varchar_pattern_ops);


--
-- Name: ccr_faculty_id_bdbba02d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ccr_faculty_id_bdbba02d ON public.ccr USING btree (faculty_id);


--
-- Name: ccr_faculty_id_bdbba02d_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ccr_faculty_id_bdbba02d_like ON public.ccr USING btree (faculty_id varchar_pattern_ops);


--
-- Name: ccr_program_id_795ebe0c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ccr_program_id_795ebe0c ON public.ccr USING btree (program_id);


--
-- Name: course_exam_stats_academic_year_caf78659; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX course_exam_stats_academic_year_caf78659 ON public.course_exam_stats USING btree (academic_year);


--
-- Name: course_exam_stats_academic_year_caf78659_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX course_exam_stats_academic_year_caf78659_like ON public.course_exam_stats USING btree (academic_year varchar_pattern_ops);


--
-- Name: course_exam_stats_course_id_f0501919; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX course_exam_stats_course_id_f0501919 ON public.course_exam_stats USING btree (course_id);


--
-- Name: course_exam_stats_course_id_f0501919_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX course_exam_stats_course_id_f0501919_like ON public.course_exam_stats USING btree (course_id varchar_pattern_ops);


--
-- Name: course_unlock_log_course_id_19924984; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX course_unlock_log_course_id_19924984 ON public.course_unlock_log USING btree (course_id);


--
-- Name: course_unlock_log_course_id_19924984_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX course_unlock_log_course_id_19924984_like ON public.course_unlock_log USING btree (course_id varchar_pattern_ops);


--
-- Name: course_unlock_log_unlocked_by_id_8d41e278; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX course_unlock_log_unlocked_by_id_8d41e278 ON public.course_unlock_log USING btree (unlocked_by_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: exam_attempt_course_id_36b4544f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exam_attempt_course_id_36b4544f ON public.exam_attempt USING btree (course_id);


--
-- Name: exam_attempt_course_id_36b4544f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exam_attempt_course_id_36b4544f_like ON public.exam_attempt USING btree (course_id varchar_pattern_ops);


--
-- Name: exam_attempt_entered_by_83e857d0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exam_attempt_entered_by_83e857d0 ON public.exam_attempt USING btree (entered_by);


--
-- Name: exam_attempt_entered_by_83e857d0_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exam_attempt_entered_by_83e857d0_like ON public.exam_attempt USING btree (entered_by varchar_pattern_ops);


--
-- Name: exam_attempt_student_id_ba856f15; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exam_attempt_student_id_ba856f15 ON public.exam_attempt USING btree (student_id);


--
-- Name: exam_attempt_student_id_ba856f15_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exam_attempt_student_id_ba856f15_like ON public.exam_attempt USING btree (student_id varchar_pattern_ops);


--
-- Name: faculty_faculty_id_fccdf2cc_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX faculty_faculty_id_fccdf2cc_like ON public.faculty USING btree (faculty_id varchar_pattern_ops);


--
-- Name: faculty_of_name_58d3d67e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX faculty_of_name_58d3d67e_like ON public.faculty_of USING btree (name varchar_pattern_ops);


--
-- Name: faculty_school_id_bb8d3be0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX faculty_school_id_bb8d3be0 ON public.faculty USING btree (school_id);


--
-- Name: ia_component_course_id_386170ce; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ia_component_course_id_386170ce ON public.ia_component USING btree (course_id);


--
-- Name: ia_component_course_id_386170ce_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ia_component_course_id_386170ce_like ON public.ia_component USING btree (course_id varchar_pattern_ops);


--
-- Name: idx_attempt_course; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_attempt_course ON public.exam_attempt USING btree (course_id);


--
-- Name: idx_attempt_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_attempt_status ON public.exam_attempt USING btree (status);


--
-- Name: idx_attempt_student; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_attempt_student ON public.exam_attempt USING btree (student_id);


--
-- Name: idx_attempt_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_attempt_type ON public.exam_attempt USING btree (attempt_type);


--
-- Name: idx_attempt_year; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_attempt_year ON public.exam_attempt USING btree (academic_year);


--
-- Name: idx_backlog_course_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_backlog_course_status ON public.student_backlog USING btree (course_id, status);


--
-- Name: idx_backlog_student_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_backlog_student_status ON public.student_backlog USING btree (student_id, status);


--
-- Name: idx_ccr_faculty; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ccr_faculty ON public.ccr USING btree (faculty_id);


--
-- Name: idx_ccr_program; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ccr_program ON public.ccr USING btree (program_id);


--
-- Name: idx_ccr_sem_year; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ccr_sem_year ON public.ccr USING btree (semester, academic_year);


--
-- Name: idx_enrolment_course; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_enrolment_course ON public.student_enrolment USING btree (course_id);


--
-- Name: idx_enrolment_student; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_enrolment_student ON public.student_enrolment USING btree (student_id);


--
-- Name: idx_faculty_school; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_faculty_school ON public.faculty USING btree (school_id);


--
-- Name: idx_marks_attempt_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_marks_attempt_type ON public.marks_entry USING btree (attempt_type);


--
-- Name: idx_marks_component; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_marks_component ON public.marks_entry USING btree (component_id);


--
-- Name: idx_marks_student; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_marks_student ON public.marks_entry USING btree (student_id);


--
-- Name: idx_program_school; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_program_school ON public.program USING btree (school_id);


--
-- Name: idx_result_course; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_result_course ON public.result_sheet USING btree (course_id);


--
-- Name: idx_result_pass_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_result_pass_status ON public.result_sheet USING btree (pass_status);


--
-- Name: idx_result_student; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_result_student ON public.result_sheet USING btree (student_id);


--
-- Name: idx_school_faculty_of; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_school_faculty_of ON public.school USING btree (faculty_of_id);


--
-- Name: idx_stats_course_year; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_stats_course_year ON public.course_exam_stats USING btree (course_id, academic_year);


--
-- Name: idx_student_program; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_student_program ON public.student USING btree (program_id);


--
-- Name: marks_entry_component_id_9bbeecac; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX marks_entry_component_id_9bbeecac ON public.marks_entry USING btree (component_id);


--
-- Name: marks_entry_entered_by_0868adc3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX marks_entry_entered_by_0868adc3 ON public.marks_entry USING btree (entered_by);


--
-- Name: marks_entry_entered_by_0868adc3_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX marks_entry_entered_by_0868adc3_like ON public.marks_entry USING btree (entered_by varchar_pattern_ops);


--
-- Name: marks_entry_student_id_fe981917; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX marks_entry_student_id_fe981917 ON public.marks_entry USING btree (student_id);


--
-- Name: marks_entry_student_id_fe981917_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX marks_entry_student_id_fe981917_like ON public.marks_entry USING btree (student_id varchar_pattern_ops);


--
-- Name: program_school_id_6918d6de; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX program_school_id_6918d6de ON public.program USING btree (school_id);


--
-- Name: result_sheet_course_id_1fc66a97; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX result_sheet_course_id_1fc66a97 ON public.result_sheet USING btree (course_id);


--
-- Name: result_sheet_course_id_1fc66a97_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX result_sheet_course_id_1fc66a97_like ON public.result_sheet USING btree (course_id varchar_pattern_ops);


--
-- Name: result_sheet_student_id_ba013eb8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX result_sheet_student_id_ba013eb8 ON public.result_sheet USING btree (student_id);


--
-- Name: result_sheet_student_id_ba013eb8_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX result_sheet_student_id_ba013eb8_like ON public.result_sheet USING btree (student_id varchar_pattern_ops);


--
-- Name: school_faculty_of_id_08a55734; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX school_faculty_of_id_08a55734 ON public.school USING btree (faculty_of_id);


--
-- Name: school_name_a6737e03_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX school_name_a6737e03_like ON public.school USING btree (name varchar_pattern_ops);


--
-- Name: student_backlog_clearing_attempt_id_db9ee9eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX student_backlog_clearing_attempt_id_db9ee9eb ON public.student_backlog USING btree (clearing_attempt_id);


--
-- Name: student_backlog_course_id_2297e166; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX student_backlog_course_id_2297e166 ON public.student_backlog USING btree (course_id);


--
-- Name: student_backlog_course_id_2297e166_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX student_backlog_course_id_2297e166_like ON public.student_backlog USING btree (course_id varchar_pattern_ops);


--
-- Name: student_backlog_origin_attempt_id_dd80848a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX student_backlog_origin_attempt_id_dd80848a ON public.student_backlog USING btree (origin_attempt_id);


--
-- Name: student_backlog_status_747bf329; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX student_backlog_status_747bf329 ON public.student_backlog USING btree (status);


--
-- Name: student_backlog_status_747bf329_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX student_backlog_status_747bf329_like ON public.student_backlog USING btree (status varchar_pattern_ops);


--
-- Name: student_backlog_student_id_8a0f55ef; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX student_backlog_student_id_8a0f55ef ON public.student_backlog USING btree (student_id);


--
-- Name: student_backlog_student_id_8a0f55ef_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX student_backlog_student_id_8a0f55ef_like ON public.student_backlog USING btree (student_id varchar_pattern_ops);


--
-- Name: student_enrolment_course_id_87cfa932; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX student_enrolment_course_id_87cfa932 ON public.student_enrolment USING btree (course_id);


--
-- Name: student_enrolment_course_id_87cfa932_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX student_enrolment_course_id_87cfa932_like ON public.student_enrolment USING btree (course_id varchar_pattern_ops);


--
-- Name: student_enrolment_student_id_afd016aa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX student_enrolment_student_id_afd016aa ON public.student_enrolment USING btree (student_id);


--
-- Name: student_enrolment_student_id_afd016aa_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX student_enrolment_student_id_afd016aa_like ON public.student_enrolment USING btree (student_id varchar_pattern_ops);


--
-- Name: student_program_id_75463063; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX student_program_id_75463063 ON public.student USING btree (program_id);


--
-- Name: student_roll_no_431a8382_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX student_roll_no_431a8382_like ON public.student USING btree (roll_no varchar_pattern_ops);


--
-- Name: student_student_id_53c349bf_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX student_student_id_53c349bf_like ON public.student USING btree (student_id varchar_pattern_ops);


--
-- Name: users_email_0ea73cca_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_email_0ea73cca_like ON public.users USING btree (email varchar_pattern_ops);


--
-- Name: users_groups_group_id_2f3517aa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_groups_group_id_2f3517aa ON public.users_groups USING btree (group_id);


--
-- Name: users_groups_user_id_f500bee5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_groups_user_id_f500bee5 ON public.users_groups USING btree (user_id);


--
-- Name: users_jlu_id_71256a92_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_jlu_id_71256a92_like ON public.users USING btree (jlu_id varchar_pattern_ops);


--
-- Name: users_user_permissions_permission_id_6d08dcd2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_permissions_permission_id_6d08dcd2 ON public.users_user_permissions USING btree (permission_id);


--
-- Name: users_user_permissions_user_id_92473840; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_permissions_user_id_92473840 ON public.users_user_permissions USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ccr ccr_faculty_id_bdbba02d_fk_faculty_faculty_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ccr
    ADD CONSTRAINT ccr_faculty_id_bdbba02d_fk_faculty_faculty_id FOREIGN KEY (faculty_id) REFERENCES public.faculty(faculty_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ccr ccr_program_id_795ebe0c_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ccr
    ADD CONSTRAINT ccr_program_id_795ebe0c_fk FOREIGN KEY (program_id) REFERENCES public.program(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: course_exam_stats course_exam_stats_course_id_f0501919_fk_ccr_course_code; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_exam_stats
    ADD CONSTRAINT course_exam_stats_course_id_f0501919_fk_ccr_course_code FOREIGN KEY (course_id) REFERENCES public.ccr(course_code) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: course_unlock_log course_unlock_log_course_id_19924984_fk_ccr_course_code; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_unlock_log
    ADD CONSTRAINT course_unlock_log_course_id_19924984_fk_ccr_course_code FOREIGN KEY (course_id) REFERENCES public.ccr(course_code) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: course_unlock_log course_unlock_log_unlocked_by_id_8d41e278_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_unlock_log
    ADD CONSTRAINT course_unlock_log_unlocked_by_id_8d41e278_fk_users_id FOREIGN KEY (unlocked_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exam_attempt exam_attempt_course_id_36b4544f_fk_ccr_course_code; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_attempt
    ADD CONSTRAINT exam_attempt_course_id_36b4544f_fk_ccr_course_code FOREIGN KEY (course_id) REFERENCES public.ccr(course_code) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exam_attempt exam_attempt_entered_by_83e857d0_fk_faculty_faculty_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_attempt
    ADD CONSTRAINT exam_attempt_entered_by_83e857d0_fk_faculty_faculty_id FOREIGN KEY (entered_by) REFERENCES public.faculty(faculty_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exam_attempt exam_attempt_student_id_ba856f15_fk_student_student_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_attempt
    ADD CONSTRAINT exam_attempt_student_id_ba856f15_fk_student_student_id FOREIGN KEY (student_id) REFERENCES public.student(student_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: faculty faculty_school_id_bb8d3be0_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.faculty
    ADD CONSTRAINT faculty_school_id_bb8d3be0_fk FOREIGN KEY (school_id) REFERENCES public.school(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: faculty faculty_user_id_c7169dec_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.faculty
    ADD CONSTRAINT faculty_user_id_c7169dec_fk FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ia_component ia_component_course_id_386170ce_fk_ccr_course_code; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ia_component
    ADD CONSTRAINT ia_component_course_id_386170ce_fk_ccr_course_code FOREIGN KEY (course_id) REFERENCES public.ccr(course_code) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: marks_entry marks_entry_component_id_9bbeecac_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marks_entry
    ADD CONSTRAINT marks_entry_component_id_9bbeecac_fk FOREIGN KEY (component_id) REFERENCES public.ia_component(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: marks_entry marks_entry_entered_by_0868adc3_fk_faculty_faculty_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marks_entry
    ADD CONSTRAINT marks_entry_entered_by_0868adc3_fk_faculty_faculty_id FOREIGN KEY (entered_by) REFERENCES public.faculty(faculty_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: marks_entry marks_entry_student_id_fe981917_fk_student_student_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marks_entry
    ADD CONSTRAINT marks_entry_student_id_fe981917_fk_student_student_id FOREIGN KEY (student_id) REFERENCES public.student(student_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: program program_school_id_6918d6de_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.program
    ADD CONSTRAINT program_school_id_6918d6de_fk FOREIGN KEY (school_id) REFERENCES public.school(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: result_sheet result_sheet_course_id_1fc66a97_fk_ccr_course_code; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.result_sheet
    ADD CONSTRAINT result_sheet_course_id_1fc66a97_fk_ccr_course_code FOREIGN KEY (course_id) REFERENCES public.ccr(course_code) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: result_sheet result_sheet_student_id_ba013eb8_fk_student_student_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.result_sheet
    ADD CONSTRAINT result_sheet_student_id_ba013eb8_fk_student_student_id FOREIGN KEY (student_id) REFERENCES public.student(student_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: school school_faculty_of_id_08a55734_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school
    ADD CONSTRAINT school_faculty_of_id_08a55734_fk FOREIGN KEY (faculty_of_id) REFERENCES public.faculty_of(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: student_backlog student_backlog_clearing_attempt_id_db9ee9eb_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_backlog
    ADD CONSTRAINT student_backlog_clearing_attempt_id_db9ee9eb_fk FOREIGN KEY (clearing_attempt_id) REFERENCES public.exam_attempt(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: student_backlog student_backlog_course_id_2297e166_fk_ccr_course_code; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_backlog
    ADD CONSTRAINT student_backlog_course_id_2297e166_fk_ccr_course_code FOREIGN KEY (course_id) REFERENCES public.ccr(course_code) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: student_backlog student_backlog_origin_attempt_id_dd80848a_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_backlog
    ADD CONSTRAINT student_backlog_origin_attempt_id_dd80848a_fk FOREIGN KEY (origin_attempt_id) REFERENCES public.exam_attempt(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: student_backlog student_backlog_student_id_8a0f55ef_fk_student_student_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_backlog
    ADD CONSTRAINT student_backlog_student_id_8a0f55ef_fk_student_student_id FOREIGN KEY (student_id) REFERENCES public.student(student_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: student_enrolment student_enrolment_course_id_87cfa932_fk_ccr_course_code; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_enrolment
    ADD CONSTRAINT student_enrolment_course_id_87cfa932_fk_ccr_course_code FOREIGN KEY (course_id) REFERENCES public.ccr(course_code) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: student_enrolment student_enrolment_student_id_afd016aa_fk_student_student_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_enrolment
    ADD CONSTRAINT student_enrolment_student_id_afd016aa_fk_student_student_id FOREIGN KEY (student_id) REFERENCES public.student(student_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: student student_program_id_75463063_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_program_id_75463063_fk FOREIGN KEY (program_id) REFERENCES public.program(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: student student_user_id_dcc2526f_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_user_id_dcc2526f_fk FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_group_id_2f3517aa_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_group_id_2f3517aa_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_user_id_f500bee5_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_f500bee5_fk FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissio_permission_id_6d08dcd2_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissio_permission_id_6d08dcd2_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissions_user_id_92473840_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_92473840_fk FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict yng2optORXtRyh6Znfnlhj3fihmNqgEnxTZuCJIWjMjamgIRbsYcW8fgskViK5n

