# Generated by Django 4.2.30 on 2026-05-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_resultsheet_idx_result_pass_status_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="marksentry",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="marksentry",
            name="attempt_type",
            field=models.CharField(
                choices=[
                    ("Regular", "Regular"),
                    ("Makeup", "Makeup"),
                    ("Backlog", "Backlog"),
                    ("SpecialBacklog", "Special Backlog"),
                ],
                default="Regular",
                help_text="Which attempt these IA marks belong to (Regular, Makeup, Backlog, etc.)",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="resultsheet",
            name="active_attempt_type",
            field=models.CharField(
                choices=[
                    ("Regular", "Regular"),
                    ("Makeup", "Makeup"),
                    ("Backlog", "Backlog"),
                    ("SpecialBacklog", "Special Backlog"),
                ],
                default="Regular",
                help_text="Which attempt type is currently active for this student+course.",
                max_length=15,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marksentry",
            unique_together={("student", "component", "attempt_type")},
        ),
        migrations.AddIndex(
            model_name="marksentry",
            index=models.Index(fields=["attempt_type"], name="idx_marks_attempt_type"),
        ),
    ]
