# Generated by Django 4.2.29 on 2026-05-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_add_attempt_type_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultsheet",
            name="ese_pass_status",
            field=models.CharField(
                choices=[
                    ("Incomplete", "Incomplete"),
                    ("Pass", "Pass"),
                    ("Fail", "Fail"),
                    ("Withheld", "Withheld"),
                ],
                default="Incomplete",
                help_text="Whether the student passed the ESE component independently.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="resultsheet",
            name="ia_pass_status",
            field=models.CharField(
                choices=[
                    ("Incomplete", "Incomplete"),
                    ("Pass", "Pass"),
                    ("Fail", "Fail"),
                    ("Withheld", "Withheld"),
                ],
                default="Incomplete",
                help_text="Whether the student passed the IA (internal) component independently.",
                max_length=12,
            ),
        ),
    ]
