# Generated by Django 4.2.29 on 2026-05-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_ccr_pass_thresholds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ccr",
            name="ese_pass_min",
            field=models.DecimalField(decimal_places=2, default=28, max_digits=6),
        ),
        migrations.AlterField(
            model_name="ccr",
            name="ia_pass_min",
            field=models.DecimalField(decimal_places=2, default=12, max_digits=6),
        ),
        migrations.AlterField(
            model_name="ccr",
            name="overall_pass_min",
            field=models.DecimalField(decimal_places=2, default=40, max_digits=6),
        ),
    ]
