# Generated by Django 4.2.30 on 2026-05-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_ccr_ese_pass_min_alter_ccr_ia_pass_min_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ccr",
            name="overall_pass_min",
        ),
        migrations.RemoveField(
            model_name="studentenrolment",
            name="ese_eligible",
        ),
    ]
